swagger: "2.0"
info:
  version: "1.0"
  title: API VERSIONING EXAMPLE
host: "localhost:10010"
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json